### ISSUE TITLE
I am unable to get queryId from hive operation

### ISSUE THREAD

**Issue by ntallapa12** [lenchv/hive-driver#24]
Are there any specific hive commands for which this works or it does not work at all? I am doing this:
const hiveQueryOperation = await this.hiveSession.executeStatement(query);
        await utils.waitUntilReady(hiveQueryOperation, false, () => {});
        const queryId = await hiveQueryOperation.getQueryId();
        
For "msk repair" query, I am able to see hive job id in HUE whereas in hive-driver, it says "GetQueryId" is not a method error.

Appreciate any inputs on this.

**Comment by lenchv** [comment]
Hi @ntallapa12 ! Probably it depends on your Hive version. Unfortunately, I didn't manage to find better documentation than source code. All API methods that can be executed by the client listed in [TCLIService.thrift](https://github.com/lenchv/hive-driver/blob/master/thrift/TCLIService.thrift#L1244).

But to find out what commands a server supports you should look through API in official Hive [repository](https://github.com/apache/hive).

For instance, here is a current API for the latest [Hive version](https://github.com/apache/hive/blob/f37c5de6c32b9395d1b34fa3c02ed06d1bfbf6eb/service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIServiceClient.java#L562).

But in [Hive 1.1.1](https://github.com/apache/hive/blob/release-1.1.1/service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIServiceClient.java) `getQueryId` method is not implemented.

So you can choose from tag list the version of Hive you use, and check what methods implemented in ThriftCLIServiceClient.java.

Also, you can check [TCLIService.thrift](https://github.com/lenchv/hive-driver/blob/master/thrift/TCLIService.thrift#L1045) responses, probably there you may find some information you are looking for.

And one more thing I should mention. Instead of result from operation, you can get [some log](https://github.com/lenchv/hive-driver/blob/master/thrift/TCLIService.thrift#L1162). To do this, you should execute `operation.setFetchType(1);` before fetching the result. And I did not implement representation of log, so you should handle raw result on your own. I mean, if you represent it as JSON using utils.getResult, ther is a probability you get an error.

**Comment by ntallapa12** [comment]
got it thanks.
